---
- name: Ensure Docker network 'app-net' exists
  docker_network:
    name: app-net
    state: present
  tags:
    - network

- name: Run MongoDB container
  docker_container:
    name: app-mongo
    image: mongo
    state: started
    restart_policy: always
    ports:
      - '27017:27017'
    volumes:
      - ./app-mongo-data:/data/db
    networks:
      - name: app-net
  tags:
    - database
    - backend
